In [1]:
import US25UW990JEPL_02 as JEPL
import copy
from datetime import datetime
import pandas as pd
import matplotlib.pyplot as plt
t=1

In [2]:
init = JEPL.Initializer(data_path='/blue/mateescu/agustinchasco/Projects/reprojersey/data',
                        code_path='/blue/mateescu/agustinchasco/Projects/reprojersey/core',
                        testing=t)

init.Directories()
init.GetFormatMap()

Initialization:

Code ipykernel_launcher.py starts.
Codes executed when testing is 1.
Running program in /blue/mateescu/agustinchasco/Projects/reprojersey/core.
Reading data in /blue/mateescu/agustinchasco/Projects/reprojersey/data.
Saving data in /blue/mateescu/agustinchasco/Projects/reprojersey/data.
Time profiling starts. Program executed on 05-02-2025 at 06:21 AM EST.

Path `/blue/mateescu/agustinchasco/Projects/reprojersey/data/ipykernel_launcher/test` already exists.

Path `/blue/mateescu/agustinchasco/Projects/reprojersey/data/view` already exists.

Loading map ipykernel_launcher_test_f4map.json in pathf4_map_path:
 /blue/mateescu/agustinchasco/Projects/reprojersey/data/ipykernel_launcher/test/ipykernel_launcher_test_f4map.json


Loading map ipykernel_launcher_test_f5map.json in pathf5_map_path:
 /blue/mateescu/agustinchasco/Projects/reprojersey/data/ipykernel_launcher/test/ipykernel_launcher_test_f5map.json


Creation of master map ipykernel_launcher_test_fmap.json in path:
 /blue/mateescu/agustinchasco/Projects/reprojersey/data/ipykernel_launcher/test/ipykernel_launcher_test_fmap.json


HTML map file named ipykernel_launcher_test_fmap.html saved in pat:
 /blue/mateescu/agustinchasco/Projects/reprojersey/data/ipykernel_launcher/test/ipykernel_launcher_test_fmap.html

In [3]:
print(f'JEPL020101 activated when testing is {init.t}. \n')
fn = ['US25UW990JEPL.01_impl_010601pdfu.txt', 'US25UW990JEPL.01_test_010601pdfu.txt'][init.t]
fp = init.TargetPath(fn)

print(f'Loading file {fn} in path: \n {fp} \n \n')
dc = JEPL.DataContainer(init, pdfu = init.TXT_reader(target_path=fp))
dc.ShowDatasets()

JEPL020101 activated when testing is 1.

Loading file US25UW990JEPL.01_test_010601pdfu.txt in path:
 /blue/mateescu/agustinchasco/Projects/reprojersey/data/US25UW990JEPL.02/test/US25UW990JEPL.01_test_010601pdfu.txt


init: <class 'US25UW990JEPL_02.Initializer'> (Not a DataFrame)

pdfu: <class 'pandas.core.frame.DataFrame'> with shape (23353, 650)

In [4]:
dc.SetKey(['pdfu'], [['f4X3', 'f4X4', 'f4X5', 'f4X35'], ['f5X3', 'f5X4', 'f5X5', 'f5X35']])

Setting key in merged dataset with 650 columns.

In [5]:
dc.pdfu.head()

,f4X1,f4X2,f4X3,f4X4,f4X5,f4X6,f4X7,f4X8,f4X9,f4X10,...,f5X328,f5X329,f5X330,f5X331,f5X332,f5X333,f5X334,f5X335,f5X336,Key
0,0,F,JE,,,JE,USA,000112755267,,,...,,,,,,,,,,JE 20120216
1,0,F,JE,,,JE,USA,00099PJS0104,JE,USA,...,,,,,,,,,,JE 20161013
2,0,F,JE,,,JE,USA,000072520700,JE,USA,...,,,,,,,,,,JE 20210726
3,0,F,JE,840,000067269606,JE,USA,000117968233,JE,USA,...,,,,,,,,,,JE84000006726960620160505
4,0,F,JE,840,000067540872,JE,USA,000067027314,XD,840,...,,,,,,,,,,JE84000006754087220151208